### ISSUE TITLE
HelloHQ plugin directory

### ISSUE THREAD

**Issue by calvinchengx** [HelloHQ/hellohq_releases#2]

**Comment by NoahJinnn** [comment]
Current Plugin directory on my Mac:
1. Config dir: `~/Library/Containers/com.example.hellohq/Data/Library/Application Support/com.HelloHQ.finance`
- The parent directory of `Plugin dir`, `Storage dir` and `plugins_manifest.json` contains all released plugins metadata

2. Plugins dir: 
`~/Library/Containers/com.example.hellohq/Data/Library/Application Support/com.HelloHQ.finance/plugins/<plugin_id>` 
- `plugin_id` is `id` field in [plugin manifest list](https://raw.githubusercontent.com/HelloHQ/hellohq_releases/main/plugins_manifest.json)

3. Storage dir:
`~/Library/Containers/com.example.hellohq/Data/Library/Application\ Support/com.HelloHQ.finance/storage`
- Store SQLite `.db` file

4. API keys dir: 
`~/Library/Containers/com.example.hellohq/Data/.finance/keys`
- Not located under `Config dir`
- Store encrypted (by `cocoon`) API keys
- Ex:
```rust
struct AlpacaKeys {
    pub key_id: String,
    pub secret: String,
}
```
